#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

# Create a .env file at the base of the new virtualenv
PROJECT_NAME=$(echo "$VIRTUAL_ENV" | awk -F '/' '{print $NF}')
ENV_CONF=$WORKON_HOME/$PROJECT_NAME/.env
echo "workon $PROJECT_NAME" > "$ENV_CONF"

# Pre-install unit test tools in the new virtualenv
pip install tox nose wheel
