#!/bin/bash
# This hook is run after every virtualenv is deactivated.

# Restore overridden cd command to its default builtin behaviour.
# Source: http://virtualenvwrapper.readthedocs.org/en/latest/tips.html#changing-the-default-behavior-of-cd
cd () {
    builtin cd "$@"
}
