#!/bin/sh
# Wrapper ensuring ssh-keygen can reach Secretive's agent for commit signing,
# even from GUI apps (like Fork) that don't inherit SSH_AUTH_SOCK.
# https://github.com/maxgoedjen/secretive/issues/795
# https://github.com/maxgoedjen/secretive/issues/404
export SSH_AUTH_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
exec /usr/bin/ssh-keygen "$@"
