"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg:color_orange)\
$username\
$sudo\
[](fg:prev_bg bg:color_yellow)\
$directory\
[](fg:prev_bg bg:color_aqua)\
$git_branch\
$git_status\
$git_state\
[](fg:prev_bg bg:color_blue)\
$python\
$package\
[](fg:prev_bg bg:color_bg1)\
[](fg:prev_bg)\
$fill\
[](fg:color_bg1)\
$cmd_duration\
$status\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '230'
color_bg1 = '16'
color_bg3 = '59'
color_blue = '30'
color_aqua = '71'
color_green = '100'
color_orange = '166'
color_purple = '132'
color_red = '160'
color_yellow = '172'

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[  $user ]($style)'

[sudo]
disabled = false
symbol = ' ' # ' ❯ '
style = 'fg:red bold'
format = '[ ](fg:red bold)[as $symbol]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)[$read_only]($read_only_style)"
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol$pyenv_prefix( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[package]
format = '[$symbol$version](fg:color_fg0 bg:color_blue)'

[cmd_duration]
style = "bg:color_bg1"
format = '[[  $duration ](fg:color_fg0 bg:color_bg1)]($style)'
min_time = 50
show_milliseconds = true

[status]
disabled = false
symbol = "\\(╯°□°）╯︵ ┻━┻ "
style = "bg:red"
format = "[](bg:prev_bg fg:red)[$status $symbol]($style)"

[fill]
symbol = '─'
style = 'fg:prev_fg'
