"$schema" = 'https://starship.rs/config-schema.json'

format = """
$sudo\
$username\
[](fg:prev_bg bg:color_yellow)\
$directory\
[](fg:prev_bg bg:color_aqua)\
$git_branch\
$git_status\
$git_state\
[](fg:prev_bg bg:color_blue)\
$python\
$package\
[](fg:prev_bg bg:color_bg1)\
[](fg:prev_bg)\
$fill\
[](fg:color_bg1)\
$cmd_duration\
$status\
$line_break\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[sudo]
disabled = false
symbol = ' '
style = 'bg:color_red fg:color_fg0'
format = '[ $symbol ]($style)[](fg:prev_bg bg:color_orange)'

[username]
show_always = true
style_user = "fg:color_fg0"
style_root = "fg:color_fg0"
format = '[  $user ]($style bg:color_orange)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)[$read_only]($read_only_style)"
fish_style_pwd_dir_length = 1
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)( $virtualenv) ](fg:color_fg0 bg:color_blue)]($style)'
generic_venv_names = ['.venv', 'venv']

[package]
format = '[$symbol$version](fg:color_fg0 bg:color_blue)'

[cmd_duration]
style = "bg:color_bg1"
format = '[[  $duration ](fg:color_fg0 bg:color_bg1)]($style)'
min_time = 50
show_milliseconds = true

[status]
disabled = false
symbol = "\\(╯°□°）╯︵ ┻━┻ "
style = "bg:color_red fg:color_fg0"
format = "[](bg:prev_bg fg:color_red)[$status $symbol]($style)"

[fill]
symbol = '─'
style = 'fg:prev_fg'
