---
name: 🪄 Autofix
"on":
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  autofix:
    uses: kdeldycke/repomatic/.github/workflows/autofix.yaml@c48893dce010cb24303044880ab40f571b7bebda # v6.21.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
