---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@94a5f543d75da9342a1ad315251988360e580ab1 # v7.17.0
