---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@90400f1be5e7a4df843b83a02dd1672cfbaccfb6 # v6.27.0
