---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@8c6a37cf588e948bcf7ba9797d940b1f5bc6b85c # v7.16.3
