---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - changelog.md
      - citation.cff
      - "docs/**"
      - pyproject.toml
      - readme.md
      - uv.lock
      - "**/*.py"

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@dd9067f15dfe8e1f2a4698d203ffc3a404155c89 # v6.22.0
