---
name: 📚 Docs
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - pyproject.toml
      - "**/*.md"
  schedule:
    - cron: "43 6 15 * *"

jobs:

  docs:
    uses: kdeldycke/repomatic/.github/workflows/docs.yaml@954c819c0e21141997c73f78a2bb7bc8633ed815 # v7.14.0
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
