---
name: 🏷️ Labels
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release
    types:
      - opened
  issues:
    types:
      - opened

jobs:

  labels:
    uses: kdeldycke/repomatic/.github/workflows/labels.yaml@8c6a37cf588e948bcf7ba9797d940b1f5bc6b85c # v7.16.3
