---
name: 🏷️ Labels
"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release
    types:
      - opened
  issues:
    types:
      - opened

jobs:

  labels:
    uses: kdeldycke/repomatic/.github/workflows/labels.yaml@94a5f543d75da9342a1ad315251988360e580ab1 # v7.17.0
