---
name: 🆕 Renovate
"on":
  workflow_dispatch:
  schedule:
    - cron: "3 17 * * 1"
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:

  renovate:
    uses: kdeldycke/repomatic/.github/workflows/renovate.yaml@c48893dce010cb24303044880ab40f571b7bebda # v6.21.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
