---
name: 🆕 Renovate
"on":
  workflow_dispatch:
  schedule:
    - cron: "3 17 * * 1"
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:

  renovate:
    uses: kdeldycke/repomatic/.github/workflows/renovate.yaml@90400f1be5e7a4df843b83a02dd1672cfbaccfb6 # v6.27.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
