---
name: 🔬 Tests
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - repomatic/**
      - tests/**
      - pyproject.toml
      - uv.lock
      - .github/workflows/tests.yaml
  pull_request:
    branches-ignore:
      - prepare-release
    paths:
      - repomatic/**
      - tests/**
      - pyproject.toml
      - uv.lock
      - .github/workflows/tests.yaml
  schedule:
    # Run tests monthly to catch regressions from dependency or environment changes.
    - cron: "17 9 1 * *"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !startsWith(github.event.head_commit.message, '[changelog] Release') }}

jobs:

  tests:
    name: Run full installation
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Install Zsh
        run: |
          brew install zsh
      - name: Force default shell
        # GitHub macOS images forces bash as default:
        # https://github.com/actions/virtual-environments/blob/0d93dd2/images/macos/provision/configuration/shell-change.sh#L3-L5
        run: |
          sudo chsh -s "$(brew --prefix zsh)/bin/zsh" root
          sudo chsh -s "$(brew --prefix zsh)/bin/zsh" "$USER"
      - name: Fix GitHub worker
        # aws-cli is already installed by hand in GitHub action runners.
        # Remove it to avoid "brew install --formula awscli" error.
        run: |
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
      - name: Run install
        run: |
          zsh ./install.sh
